- name: Check for yarn.lock file
  stat:
    path: "{{ zuul_work_dir }}/yarn.lock"
    get_checksum: false
    get_mime: false
    get_md5: false
  register: yarn_lock

- name: Install yarn if needed
  include: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
  when:
    - yarn_lock.stat.exists
