- name: Install .pydistutils.cfg configuration in homedir
  template:
    dest: ~/.pydistutils.cfg
    mode: 0644
    src: .pydistutils.cfg.j2

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.{{ ansible_architecture }}.yaml"
    - "{{ ansible_distribution }}.yaml"
    - "{{ ansible_os_family }}.yaml"
    - "default.yaml"

- name: Install /etc/pip.conf configuration
  become: yes
  template:
    dest: /etc/pip.conf
    group: root
    mode: 0644
    owner: root
    src: etc/pip.conf.j2

- name: Setup distribution specific packaging mirrors
  include: "{{ item }}"
  static: no
  with_first_found:
    - "mirror/{{ ansible_distribution }}.yaml"
    - "mirror/{{ ansible_os_family }}.yaml"
    - "mirror/default.yaml"
