- name: Run tox without tests
  command: "{{ tox_executable }} --notest -e{{ tox_envlist }}"
  args:
    chdir: "{{ zuul_work_dir }}"
  environment: "{{ tox_environment|combine(tox_constraints_env|default({})) }}"

# TODO(mordred) handle tox_envlist being a list
- name: Install any sibling python packages
  tox_install_sibling_packages:
    tox_envlist: "{{ tox_envlist }}"
    tox_constraints_file: "{{ tox_constraints_file | default(omit) }}"
    project_dir: "{{ zuul_work_dir }}"
    projects: "{{ zuul.projects.values() | selectattr('required') | list }}"
