- name: Configure a multi node environment
  hosts: all
  tasks:
    # TODO: Add groups['all'] | length > 1 conditional when the truncated JSON
    # issue is resolved, see:
    # - https://github.com/ansible/ansible/issues/30385
    # - https://review.openstack.org/#/c/504238/
    - name: Set up multi-node known hosts
      include_role:
        name: multi-node-known-hosts

    - name: Set up multi-node hosts file
      include_role:
        name: multi-node-hosts-file

    - name: Set up multi-node firewall
      include_role:
        name: multi-node-firewall

- name: Configure multi-node networking switch and peer nodes
  hosts:
    - switch
    - peers
  roles:
    - multi-node-bridge

- name: Copy the build ssh key to authorized_keys on all hosts for root
  hosts: all
  roles:
    - copy-build-sshkey
